"""add download_id to book model

Revision ID: 1f7f448dc20c
Revises: d5dc9e521a12
Create Date: 2025-09-17 01:34:54.344517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7f448dc20c'
down_revision = 'd5dc9e521a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_download_id'), ['download_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_download_id'))
        batch_op.drop_column('download_id')

    # ### end Alembic commands ###
