"""indexers table

Revision ID: c4e5f68585a6
Revises: 73afaa3bc41c
Create Date: 2025-09-16 23:13:05.797511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e5f68585a6'
down_revision = '73afaa3bc41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('indexer_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('indexer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexer_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexer_name'))

    op.drop_table('indexer')
    # ### end Alembic commands ###
