"""download clients table

Revision ID: d5dc9e521a12
Revises: c4e5f68585a6
Create Date: 2025-09-16 23:24:04.506210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5dc9e521a12'
down_revision = 'c4e5f68585a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('client_type', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_client_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_client_name'))

    op.drop_table('download_client')
    # ### end Alembic commands ###
